version: "3.8"
services:
  typo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NAME=production
      - URL=https://typo.kenin.dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.typo.rule=Host(`typo.kenin.dev`)"
      - "traefik.http.services.typo.loadbalancer.server.port=8000"
    networks:
      - redis
      - traefik_default
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - redis

volumes:
  redis-data:

networks:
  traefik_default:
    external: true
  redis:
